apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    app: admin
spec:
  type: NodePort
  selector:
    app: admin
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30001