apiVersion: v1
kind: Service
metadata:
  name: postgres-master-service
spec:
  selector:
    app: postgres-master
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-slave-service
spec:
  selector:
    app: postgres-slave
  ports:
  - port: 5432
    targetPort: 5432